### ISSUE TITLE
tidyquant with grouped data frame?

### ISSUE THREAD

**Issue by DavisVaughan** [mdancho84/tidyquant#3]
Love the idea of this package! I am not sure if the intention of tq_mutate was to closely mimic dplyr's mutate, but I am having the following issue with it and wanted to ask a quick question. Using the tidyquant example from github, I wanted to create scalable code where you use tidyquant to load in multiple stocks' stock.prices at once into a nested data frame, and then use tq_mutate() to run runSD() on each of them. I got that to work, but the code is quite long and kinda messy with the nested pipes.

I then unnest() the code, and use dplyr's group_by() function to create a large tidy grouped data frame. I can use mutate on the grouped data frame to add the running sd's to each, but tq_mutate fails. The mutate option is pretty clean looking, but I was wondering if you had wanted tq_mutate to work on something like this.

```
# Example from github, with unnest() removed to keep as list column
x <- tibble(symbol = c("FB", "AMZN", "NFLX", "GOOGL")) %>%
     mutate(stock.prices = map(.x = symbol,
                               .f = ~ tq_get(.x, get = "stock.prices")))

# For each tibble in the nested tibble, perform the function runSD on the Ad column
x %>% mutate(stock.prices = stock.prices %>% map(~tq_mutate(data = .x,
                                                           ohlc_fun = Ad, 
                                                           mutate_fun = runSD)))

# What about an easier way?

# In the unnested form
y <- unnest(x)

# First group by the symbols
y <- group_by(y, symbol)

# dplyr mutate seems to know what to do here
y %>% mutate(sd = runSD(adjusted))

# I thought tq_mutate should work, but it doesn't
y %>% tq_mutate(ohlc_fun = Ad, mutate_fun = runSD)

# Some debugging results
debugonce(as_xts_)
y %>% tq_mutate(ohlc_fun = Ad, mutate_fun = runSD)
#Stepping through, it seems to fail during the call to 'xts::xts[,-1]' because of the added groups
#select_() will add the grouping back to the single column of dates as the first column. Now the ordering is out of whack when converting to xts

"
Adding missing grouping variables: `symbol`
Error in sum(x[beg:(n + beg - 1)]) : 
  invalid type (character) of argument
"
```

**Comment by DavisVaughan** [comment]
Fixing code block output. Didn't render correctly first time. My bad.

**Comment by mdancho84** [comment]
Davis,

Good pickup. Let me check this out tomorrow AM. 

Thanks, Matt

**Comment by mdancho84** [comment]
This is definitely a bug with grouped data frames. The good news is it can be fixed. Look for a patch soon.

**Comment by mdancho84** [comment]
@DavisVaughan 

I've updated the development version with a patch that enables `tq_mutate` and `tq_transform` to work seamlessly with `dplyr::group_by`. The tests I've run are as follows:

- Tested using `group_by` with both `tq_mutate` and `tq_transform` to ensure results are the same as using `group_by` with `mutate` from `dplyr` (note that `tq_transform` will only return the group column(s), date column and new column(s); `tq_mutate` returns the same result as `mutate`)
- Tested using your example
- Tested with zero, one, and multiple groups

Please test it out. Make sure it works to your satisfaction. I aim to please, so let me know if there is still something that needs worked out. If it's all good, let me know and I will close out the issue.

You can download the development version with `devtools`:

```
# install.packages("devtools") # uncomment if not installed
devtools::install_github("mdancho84/tidyquant")
```

Also, you may need to update some of the dependencies prior to installing the dev version of `tidyquant`. I had to update `tidyr` before I ran the `devtools::install_github("mdancho84/tidyquant")`. If using RStudio, just "update all" packages prior to updating just to be on the safe side. Otherwise, you may get an error when downloading due to a conflict.

**Comment by DavisVaughan** [comment]
@mdancho84 

This is great! That example works like a charm now. In terms of this specific issue, you can close it.

I did have two other ideas though, just something that I thought I might bring to your attention.

* When running the code `y %>% tq_mutate(ohlc_fun = Ad, mutate_fun = runSD)`, the resulting tibble has `v1` as the new column name. `y %>% mutate(sd = runSD(adjusted))` allows me to specify `sd` as the column name, which would be efficient if more calculations were to be immediately done on the sd column through piping. Obviously the same `sd =` technique is not going to work in your case, but perhaps another parameter such as `col_name =` or `var_name` would work to where the user could specify the name of the resulting column in the `tq_mutate` call. Just a thought and really a minor quirk.

* Some functions like `rollmean` don't work right out of the box if you are attempting to use them with `tq_mutate`. Specifically, using the grouped `y` from the example above, and running `y %>% tq_mutate(ohlc_fun = Ad, mutate_fun = rollmean, k = 10)` returns an error that two tibbles can't be joined. `rollmean` is doing what it is supposed to do by default, by not padding with NAs so the result is shorter in length than the original tibble. However, some people might not be familiar with that, and get frustrated, unaware that `y %>% tq_mutate(ohlc_fun = Ad, mutate_fun = rollmean, k = 10, fill = NA, align = "right")` would work. Since `tq_mutate` is almost always going to be working on a tibble, and the alignment and fill would be needed, perhaps some sensible defaults could be set for `fill` and `align`? Again, it's nothing code breaking, but just a personal preference while messing around with the package.

Great work though! And thanks again.

**Comment by mdancho84** [comment]
@DavisVaughan

Glad it's working. I will close out. Regarding your comments, let me see what I can do. Here's my specific comments:

1. I will incorporate in 0.3.0. The  tough part about column names is that sometimes there is more than one column being added, which is why `mutate` doesn't work with say `BBands`. I could add a generic column name field, and as long as the user enters the appropriate number of column names using a character vector, `col_names = c("col_one", "col_two")`, then this would work. However, if the correct number of column names is not specified I guess the user gets the default generated comments.

2. Yeah, this is the problem with inconsistent functions, especially with the `na.pad` of `fill` arguments. I'll see what I can do, but it may be best to leave it up to the user to get it right in this instance.
