### ISSUE TITLE
errors when coercing from tibble to xts

### ISSUE THREAD

**Issue by madsurgeon** [mdancho84/tidyquant#6]
Hi,

following the vignette, I end up with the following error:
`
> aapl_prices %>% as_xts()
Error in as_xts_(x, date_col, ...) : 
  date_col = NULL is invalid within names(x)
> aapl_prices %>% select(-date) %>% as_xts(date_col = row.names)
Error in as_xts_(x, date_col, ...) : 
  date_col = row.names is invalid within names(x)
> aapl_prices %>% select(-date) %>% as_xts(date_col = aapl_prices$date)
Error in as_xts_(x, date_col, ...) : 
  date_col = aapl_prices$date is invalid within names(x)
> aapl_prices %>% select(open:close) %>% as_xts(date_col = aapl_prices$date)
Error in as_xts_(x, date_col, ...) : 
  date_col = aapl_prices$date is invalid within names(x)
`

So e.g. to display a candlestick chart in dygraph I need to do the rather unelegant:
`
dygraph(as.xts(aapl_prices[,c(2:5)], order.by = as.Date(sapply(aapl_prices[,1], function(x) {as.numeric(x)}), origin="1970-01-01"))) %>% dyCandlestick()
`

This is even true for just one line using the adjusted prices:
`
dygraph(as.xts(aapl_prices$adjusted, order.by = as.Date(sapply(aapl_prices$date, function(x) {as.numeric(x)}), origin="1970-01-01")))
`

You see that I am not yet fully immersed in the tidyverse so when things don't work I help myself with standard R. But I am sure this should be possible to do much more simple and elegant.

**Comment by mdancho84** [comment]
It can be a little tricky if you aren't used to the tidyverse. Try this:

'''
as_xts(aapl_prices, date_col = date)
'''

What is happening behind the scenes is the data frame is being converted to an xts object, and in order to do so the xts objects needs the date column from your aapl_prices (it uses the dates to create the xts row names). Make sure the date column is a date class (not character), which it should be in if you used 'tq_get' to retrieve the prices. Otherwise you will get another error. 

Let me know if you still have any troubles. I will not close out until we get it working :)

**Comment by madsurgeon** [comment]
Perfect!
`
dygraph(as_xts(aapl_prices, date_col = date)[,1:4]) %>% dyCandlestick()
`
works :-)
Thank you!

**Comment by mdancho84** [comment]
Great!
